# config_pyiot.yaml 
# IoT Configuration
config_pyiot:
  mqtt:
    server_url: "broker.mqttdashboard.com"        # http://www.hivemq.com/demos/websocket-client/
    # server_url: "test.mosquitto.org"			  # Alternative to HiveMQ
    server_port: 1883
    topic_sub: "/eyrc/vb/eyantraiitb/orders"          # <unique_id> = xYzqLm
    topic_pub: "/eyrc/vb/eyantraiitb/orders"          # <unique_id> = xYzqLm
    qos: 0

    sub_cb_ros_topic: "/ros_iot_bridge/mqtt/sub"   # ROS nodes can listen to this topic to receive data from MQTT

  google_apps:
    spread_sheet_id :  "AKfycbzf3-m8t37SdhbLQ_VF7lscs1nn-PoX4gGOYOZRgxCOl2RYU9oUmFJd/exec"

